#!/usr/bin/env python3
"""Regenerate the Unicode character-property table from the *system* CPython.

The table is byte-exact with THIS interpreter's str.is* predicates, so it matches
whatever Unicode version the differential gate's CPython uses -- no vendored UCD
file, no unicode.org fetch, no version-skew between rustc's bundled UCD and
CPython's. (rustc's `char::is_*` lags/leads CPython's Unicode version, which is
exactly how the old `char::is_alphabetic`/`is_uppercase` path diverged.)

Each codepoint maps to one u8 of flags:
    bits 0-1  numeric rank  3=Decimal 2=Digit 1=Numeric 0=none  (is{decimal,digit,numeric})
    bits 2-3  case class    1=lower   2=upper 3=title  0=none    (isupper / islower)
    bit  4    alpha                                              (isalpha / isalnum)
    bit  5    space                                              (isspace)

The case class is the per-character UPPER/LOWER/TITLE flag, reconstructed from
CPython's *string* algorithm (`("A"+c).isupper()` is False iff c is lower-or-
title; `("a"+c).islower()` is False iff c is upper-or-title). This reproduces
str.isupper()/islower() exactly -- including titlecase digraphs like 'DZ' (U+01C5)
that block isupper.

This is a MANUAL tool, NOT a build step: `cargo build` only ever sees the
committed `unicode_char_table.rs`, so the runtime build stays hermetic (no Python
dependency). Rerun on a CPython/Unicode bump:

    python3 crates/runtime/tools/gen_unicode_tables.py \
        > crates/runtime/src/string/unicode_char_table.rs
"""
from __future__ import annotations

import sys
import unicodedata

FLAG_ALPHA = 0x10
FLAG_SPACE = 0x20


def char_flags(cp: int) -> int:
    """Pack the str.is* properties of one codepoint into a u8 (see module docstring)."""
    c = chr(cp)

    if c.isdecimal():
        rank = 3
    elif c.isdigit():
        rank = 2
    elif c.isnumeric():
        rank = 1
    else:
        rank = 0

    # Per-char case flag from CPython's string algorithm; the masks are mutually
    # exclusive, so (lower-or-title, upper-or-title) reconstructs all three.
    lower_or_title = not ("A" + c).isupper()
    upper_or_title = not ("a" + c).islower()
    if lower_or_title and upper_or_title:
        case = 3  # title
    elif lower_or_title:
        case = 1  # lower
    elif upper_or_title:
        case = 2  # upper
    else:
        case = 0

    f = rank | (case << 2)
    if c.isalpha():
        f |= FLAG_ALPHA
    if c.isspace():
        f |= FLAG_SPACE
    return f


def main() -> None:
    # Coalesce equal-flag runs into (start, end_inclusive, flags).
    ranges: list[list[int]] = []
    for cp in range(0x110000):
        f = char_flags(cp)
        if f == 0:
            continue
        if ranges and ranges[-1][2] == f and ranges[-1][1] + 1 == cp:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, f])

    w = sys.stdout.write
    w("// @generated by tools/gen_unicode_tables.py from system CPython. DO NOT EDIT.\n")
    w(f"// Unicode {unicodedata.unidata_version}, CPython {sys.version.split()[0]}.\n")
    w("// flags u8: bits0-1 numeric rank (3=Decimal,2=Digit,1=Numeric), bits2-3 case\n")
    w("// class (1=lower,2=upper,3=title), bit4 alpha, bit5 space. See string/predicates.rs.\n\n")
    w("/// Sorted, non-overlapping `(start, end_inclusive, flags)` Unicode property ranges.\n")
    w("pub(crate) static CHAR_TABLE: &[(u32, u32, u8)] = &[\n")
    for start, end, f in ranges:
        w(f"    (0x{start:04X}, 0x{end:04X}, 0x{f:02X}),\n")
    w("];\n")
    sys.stderr.write(
        f"generated {len(ranges)} ranges (Unicode {unicodedata.unidata_version})\n"
    )


if __name__ == "__main__":
    main()
