#!/usr/bin/env python3
"""Regenerate the Numeric_Type rank table from the *system* CPython.

The table is byte-exact with THIS interpreter's str.is{decimal,digit,numeric},
so it matches whatever Unicode version the differential gate's CPython uses --
no vendored UCD file, no unicode.org fetch, no version-skew hazard.

This is a MANUAL tool, NOT a build step: `cargo build` only ever sees the
committed `numeric_type_table.rs`, so the runtime build stays hermetic (no
Python dependency). Rerun on a CPython/Unicode bump:

    python3 crates/runtime/tools/gen_numeric_table.py \
        > crates/runtime/src/string/numeric_type_table.rs
"""
from __future__ import annotations

import sys
import unicodedata


def rank(cp: int) -> int:
    """Numeric_Type rank of a codepoint: 3=Decimal, 2=Digit, 1=Numeric, 0=none.

    Queries the very predicates we replicate, so the table is correct by
    construction. The three predicates are strictly nested
    (isdecimal => isdigit => isnumeric), which is why a single rank suffices.
    """
    c = chr(cp)
    if c.isdecimal():
        return 3
    if c.isdigit():
        return 2
    if c.isnumeric():
        return 1
    return 0


def main() -> None:
    # Coalesce equal-rank runs into (start, end_inclusive, rank).
    ranges: list[list[int]] = []
    for cp in range(0x110000):
        r = rank(cp)
        if r == 0:
            continue
        if ranges and ranges[-1][2] == r and ranges[-1][1] + 1 == cp:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, r])

    w = sys.stdout.write
    w("// @generated by tools/gen_numeric_table.py from system CPython. DO NOT EDIT.\n")
    w(f"// Unicode {unicodedata.unidata_version}, CPython {sys.version.split()[0]}.\n")
    w("// rank: 3=Decimal (isdecimal), 2=Digit (isdigit), 1=Numeric (isnumeric).\n")
    w("// Predicates compare the rank with >= thresholds; see string/predicates.rs.\n\n")
    w("/// Sorted, non-overlapping `(start, end_inclusive, rank)` Numeric_Type ranges.\n")
    w("pub(crate) static NUMERIC_TYPE_RANGES: &[(u32, u32, u8)] = &[\n")
    for start, end, r in ranges:
        w(f"    (0x{start:04X}, 0x{end:04X}, {r}),\n")
    w("];\n")
    sys.stderr.write(
        f"generated {len(ranges)} ranges (Unicode {unicodedata.unidata_version})\n"
    )


if __name__ == "__main__":
    main()
