#!/usr/bin/env python3
"""Regenerate the single-byte charmap codec tables from the *system* CPython.

Every byte->codepoint mapping is taken from THIS interpreter's own codecs, so the
tables are byte-exact with whatever the differential gate's CPython produces -- no
vendored charmaps, no version skew. Each codec is a 256-entry `[u16; 256]` table
(`0xFFFF` = undefined byte, which decodes to a `UnicodeDecodeError`). Only
genuinely single-byte (stateless charmap) codecs belong here; multi-byte CJK
codecs (`shift_jis`/`gbk`/`big5`) are deliberately out of scope.

The encoding-name lookup table reproduces CPython's aliases for the included
codecs, normalized exactly like `string/codec.rs::normalize` (lowercased, with
`-`/`_`/space stripped).

This is a MANUAL tool, NOT a build step: `cargo build` only ever sees the
committed `codec_tables.rs`, so the runtime build stays hermetic. Rerun on a
CPython bump:

    python3 crates/runtime/tools/gen_codec_tables.py \
        > crates/runtime/src/string/codec_tables.rs
"""
from __future__ import annotations

import codecs as _codecs
import sys
from encodings.aliases import aliases as _ALIASES

UNDEF = 0xFFFF

# Single-byte charmap codecs to include. iso-8859-1/ascii/utf-* are handled
# directly in codec.rs and are intentionally absent. Order fixes the table index.
CODECS = [
    # ISO 8859 family (no iso-8859-1: that is latin-1, handled in codec.rs).
    "iso8859_2", "iso8859_3", "iso8859_4", "iso8859_5", "iso8859_6",
    "iso8859_7", "iso8859_8", "iso8859_9", "iso8859_10", "iso8859_11",
    "iso8859_13", "iso8859_14", "iso8859_15", "iso8859_16",
    # Windows code pages.
    "cp1250", "cp1251", "cp1252", "cp1253", "cp1254", "cp1255", "cp1256",
    "cp1257", "cp1258",
    # KOI8.
    "koi8_r", "koi8_u", "koi8_t",
    # Macintosh.
    "mac_cyrillic", "mac_greek", "mac_iceland", "mac_latin2", "mac_roman",
    "mac_turkish",
    # DOS / IBM single-byte code pages.
    "cp437", "cp737", "cp775", "cp850", "cp852", "cp855", "cp857", "cp858",
    "cp860", "cp861", "cp862", "cp863", "cp864", "cp865", "cp866", "cp869",
    "cp874",
]

# Names handled directly in codec.rs (post-normalize); never reassign these.
HANDLED = {
    "utf8", "ascii", "usascii", "646", "latin1", "iso88591", "latin", "l1",
    "8859", "cp819", "utf16", "u16", "utf", "utf16le", "unicodelittleunmarked",
    "utf16be", "unicodebigunmarked", "utf32", "u32", "utf32le", "utf32be",
}


def normalize(name: str) -> str:
    """Match string/codec.rs::normalize: lowercase, strip '-'/'_'/' '."""
    return "".join(c for c in name.lower() if c not in "-_ ")


def build_table(name: str) -> list[int]:
    """256-entry byte->codepoint table; UNDEF for bytes that fail to decode."""
    table = []
    for b in range(256):
        try:
            s = bytes([b]).decode(name)
        except UnicodeDecodeError:
            table.append(UNDEF)
            continue
        assert len(s) == 1, f"{name}: byte {b:#x} is not single-char (multibyte?)"
        cp = ord(s)
        assert cp <= 0xFFFF, f"{name}: byte {b:#x} -> U+{cp:04X} exceeds BMP"
        assert not (0xD800 <= cp <= 0xDFFF), f"{name}: surrogate target"
        assert cp != UNDEF, f"{name}: byte {b:#x} maps to the UNDEF sentinel"
        table.append(cp)
    return table


def main() -> None:
    tables: list[tuple[str, list[int]]] = []
    names: dict[str, int] = {}  # normalized name -> table index

    for name in CODECS:
        try:
            _codecs.lookup(name)
        except LookupError:
            sys.stderr.write(f"skip (unavailable on this CPython): {name}\n")
            continue
        idx = len(tables)
        canonical = name.replace("_", "-")
        tables.append((canonical, build_table(name)))

        # Collect every spelling: module name, hyphenated canonical, and all
        # CPython aliases pointing at this codec module.
        spellings = {name, canonical}
        spellings.update(a for a, mod in _ALIASES.items() if mod == name)
        for spelling in spellings:
            key = normalize(spelling)
            if not key or key in HANDLED:
                continue
            if key in names and names[key] != idx:
                raise SystemExit(
                    f"alias collision: {key!r} -> {tables[names[key]][0]} and {canonical}"
                )
            names[key] = idx

    w = sys.stdout.write
    w("// @generated by tools/gen_codec_tables.py from system CPython. DO NOT EDIT.\n")
    w(f"// Single-byte charmap codecs, CPython {sys.version.split()[0]}.\n")
    w("// Each table is byte -> codepoint; 0xFFFF marks an undefined byte.\n")
    w("// See string/codec.rs (decode_single_byte / encode_single_byte).\n\n")

    w("/// Undefined-byte sentinel in the decode tables.\n")
    w("pub(crate) const UNDEF: u16 = 0xFFFF;\n\n")

    w("/// One `[u16; 256]` byte->codepoint table per single-byte codec.\n")
    w("pub(crate) static SINGLE_BYTE_TABLES: &[[u16; 256]] = &[\n")
    for canonical, table in tables:
        w(f"    // {canonical}\n    [\n")
        for row_start in range(0, 256, 8):
            row = table[row_start:row_start + 8]
            w("        " + " ".join(f"0x{cp:04X}," for cp in row) + "\n")
        w("    ],\n")
    w("];\n\n")

    w("/// Canonical codec name per table index (for exception messages).\n")
    w("pub(crate) static SINGLE_BYTE_CODEC_NAMES: &[&str] = &[\n")
    for canonical, _ in tables:
        w(f"    {canonical!r},\n".replace("'", '"'))
    w("];\n\n")

    w("/// Normalized encoding name -> table index, sorted for binary search.\n")
    w("/// Names are normalized like codec.rs::normalize (lowercase, no -/_/space).\n")
    w("pub(crate) static SINGLE_BYTE_NAMES: &[(&str, usize)] = &[\n")
    for key in sorted(names):
        w(f'    ("{key}", {names[key]}),\n')
    w("];\n")

    sys.stderr.write(
        f"generated {len(tables)} single-byte codecs, {len(names)} name aliases\n"
    )


if __name__ == "__main__":
    main()
